[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests",]
# comment out --cov to use debugger
# addopts = "--cov=massgit --cov-report html --cov-branch"

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
    "@abstractmethod",
    "@abc.abstractmethod",
]
omit = [
    "massgit/__main__.py",
]
