[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests",]
# comment out --cov to use debugger
# addopts = "--cov=massgit --cov-report html --cov-branch"

[tool.coverage.report]
exclude_lines = [
    "@abstractmethod",
    "@abc.abstractmethod",
]
